//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Métadonnées de relation EDM

[assembly: EdmRelationshipAttribute("TPAutoEcoleModel", "FK_Lecon_Eleve", "Eleve", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TPAutoEcoleDAO.Eleve), "Lecon", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TPAutoEcoleDAO.Lecon), true)]
[assembly: EdmRelationshipAttribute("TPAutoEcoleModel", "FK_Lecon_Voiture", "Voiture", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TPAutoEcoleDAO.Voiture), "Lecon", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TPAutoEcoleDAO.Lecon), true)]

#endregion

namespace TPAutoEcoleDAO
{
    #region Contextes
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    public partial class TPAutoEcoleEntities : ObjectContext
    {
        #region Constructeurs
    
        /// <summary>
        /// Initialise un nouvel objet TPAutoEcoleEntities à l'aide de la chaîne de connexion trouvée dans la section 'TPAutoEcoleEntities' du fichier de configuration d'application.
        /// </summary>
        public TPAutoEcoleEntities() : base("name=TPAutoEcoleEntities", "TPAutoEcoleEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet TPAutoEcoleEntities.
        /// </summary>
        public TPAutoEcoleEntities(string connectionString) : base(connectionString, "TPAutoEcoleEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet TPAutoEcoleEntities.
        /// </summary>
        public TPAutoEcoleEntities(EntityConnection connection) : base(connection, "TPAutoEcoleEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Méthodes partielles
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propriétés ObjectSet
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<Eleve> Eleve
        {
            get
            {
                if ((_Eleve == null))
                {
                    _Eleve = base.CreateObjectSet<Eleve>("Eleve");
                }
                return _Eleve;
            }
        }
        private ObjectSet<Eleve> _Eleve;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<Lecon> Lecon
        {
            get
            {
                if ((_Lecon == null))
                {
                    _Lecon = base.CreateObjectSet<Lecon>("Lecon");
                }
                return _Lecon;
            }
        }
        private ObjectSet<Lecon> _Lecon;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<Voiture> Voiture
        {
            get
            {
                if ((_Voiture == null))
                {
                    _Voiture = base.CreateObjectSet<Voiture>("Voiture");
                }
                return _Voiture;
            }
        }
        private ObjectSet<Voiture> _Voiture;

        #endregion

        #region Méthodes AddTo
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet Eleve. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToEleve(Eleve eleve)
        {
            base.AddObject("Eleve", eleve);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet Lecon. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToLecon(Lecon lecon)
        {
            base.AddObject("Lecon", lecon);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet Voiture. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToVoiture(Voiture voiture)
        {
            base.AddObject("Voiture", voiture);
        }

        #endregion

    }

    #endregion

    #region Entités
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TPAutoEcoleModel", Name="Eleve")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Eleve : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet Eleve.
        /// </summary>
        /// <param name="id">Valeur initiale de la propriété id.</param>
        /// <param name="nom">Valeur initiale de la propriété nom.</param>
        /// <param name="prenom">Valeur initiale de la propriété prenom.</param>
        /// <param name="dateInscription">Valeur initiale de la propriété dateInscription.</param>
        public static Eleve CreateEleve(global::System.Guid id, global::System.String nom, global::System.String prenom, global::System.DateTime dateInscription)
        {
            Eleve eleve = new Eleve();
            eleve.id = id;
            eleve.nom = nom;
            eleve.prenom = prenom;
            eleve.dateInscription = dateInscription;
            return eleve;
        }

        #endregion

        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Guid _id;
        partial void OnidChanging(global::System.Guid value);
        partial void OnidChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nom
        {
            get
            {
                return _nom;
            }
            set
            {
                OnnomChanging(value);
                ReportPropertyChanging("nom");
                _nom = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nom");
                OnnomChanged();
            }
        }
        private global::System.String _nom;
        partial void OnnomChanging(global::System.String value);
        partial void OnnomChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String prenom
        {
            get
            {
                return _prenom;
            }
            set
            {
                OnprenomChanging(value);
                ReportPropertyChanging("prenom");
                _prenom = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("prenom");
                OnprenomChanged();
            }
        }
        private global::System.String _prenom;
        partial void OnprenomChanging(global::System.String value);
        partial void OnprenomChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String adresse
        {
            get
            {
                return _adresse;
            }
            set
            {
                OnadresseChanging(value);
                ReportPropertyChanging("adresse");
                _adresse = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("adresse");
                OnadresseChanged();
            }
        }
        private global::System.String _adresse;
        partial void OnadresseChanging(global::System.String value);
        partial void OnadresseChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ville
        {
            get
            {
                return _ville;
            }
            set
            {
                OnvilleChanging(value);
                ReportPropertyChanging("ville");
                _ville = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ville");
                OnvilleChanged();
            }
        }
        private global::System.String _ville;
        partial void OnvilleChanging(global::System.String value);
        partial void OnvilleChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String cp
        {
            get
            {
                return _cp;
            }
            set
            {
                OncpChanging(value);
                ReportPropertyChanging("cp");
                _cp = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("cp");
                OncpChanged();
            }
        }
        private global::System.String _cp;
        partial void OncpChanging(global::System.String value);
        partial void OncpChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime dateInscription
        {
            get
            {
                return _dateInscription;
            }
            set
            {
                OndateInscriptionChanging(value);
                ReportPropertyChanging("dateInscription");
                _dateInscription = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dateInscription");
                OndateInscriptionChanged();
            }
        }
        private global::System.DateTime _dateInscription;
        partial void OndateInscriptionChanging(global::System.DateTime value);
        partial void OndateInscriptionChanged();

        #endregion

    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TPAutoEcoleModel", "FK_Lecon_Eleve", "Lecon")]
        public EntityCollection<Lecon> Lecon
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Lecon>("TPAutoEcoleModel.FK_Lecon_Eleve", "Lecon");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Lecon>("TPAutoEcoleModel.FK_Lecon_Eleve", "Lecon", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TPAutoEcoleModel", Name="Lecon")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Lecon : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet Lecon.
        /// </summary>
        /// <param name="dateLecon">Valeur initiale de la propriété dateLecon.</param>
        /// <param name="duree">Valeur initiale de la propriété duree.</param>
        /// <param name="idEleve">Valeur initiale de la propriété idEleve.</param>
        /// <param name="idVoiture">Valeur initiale de la propriété idVoiture.</param>
        public static Lecon CreateLecon(global::System.DateTime dateLecon, global::System.Int32 duree, global::System.Guid idEleve, global::System.Guid idVoiture)
        {
            Lecon lecon = new Lecon();
            lecon.dateLecon = dateLecon;
            lecon.duree = duree;
            lecon.idEleve = idEleve;
            lecon.idVoiture = idVoiture;
            return lecon;
        }

        #endregion

        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime dateLecon
        {
            get
            {
                return _dateLecon;
            }
            set
            {
                OndateLeconChanging(value);
                ReportPropertyChanging("dateLecon");
                _dateLecon = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dateLecon");
                OndateLeconChanged();
            }
        }
        private global::System.DateTime _dateLecon;
        partial void OndateLeconChanging(global::System.DateTime value);
        partial void OndateLeconChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 duree
        {
            get
            {
                return _duree;
            }
            set
            {
                OndureeChanging(value);
                ReportPropertyChanging("duree");
                _duree = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("duree");
                OndureeChanged();
            }
        }
        private global::System.Int32 _duree;
        partial void OndureeChanging(global::System.Int32 value);
        partial void OndureeChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> estEffectuee
        {
            get
            {
                return _estEffectuee;
            }
            set
            {
                OnestEffectueeChanging(value);
                ReportPropertyChanging("estEffectuee");
                _estEffectuee = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("estEffectuee");
                OnestEffectueeChanged();
            }
        }
        private Nullable<global::System.Boolean> _estEffectuee;
        partial void OnestEffectueeChanging(Nullable<global::System.Boolean> value);
        partial void OnestEffectueeChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid idEleve
        {
            get
            {
                return _idEleve;
            }
            set
            {
                if (_idEleve != value)
                {
                    OnidEleveChanging(value);
                    ReportPropertyChanging("idEleve");
                    _idEleve = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idEleve");
                    OnidEleveChanged();
                }
            }
        }
        private global::System.Guid _idEleve;
        partial void OnidEleveChanging(global::System.Guid value);
        partial void OnidEleveChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid idVoiture
        {
            get
            {
                return _idVoiture;
            }
            set
            {
                if (_idVoiture != value)
                {
                    OnidVoitureChanging(value);
                    ReportPropertyChanging("idVoiture");
                    _idVoiture = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idVoiture");
                    OnidVoitureChanged();
                }
            }
        }
        private global::System.Guid _idVoiture;
        partial void OnidVoitureChanging(global::System.Guid value);
        partial void OnidVoitureChanged();

        #endregion

    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TPAutoEcoleModel", "FK_Lecon_Eleve", "Eleve")]
        public Eleve Eleve
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Eleve>("TPAutoEcoleModel.FK_Lecon_Eleve", "Eleve").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Eleve>("TPAutoEcoleModel.FK_Lecon_Eleve", "Eleve").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Eleve> EleveReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Eleve>("TPAutoEcoleModel.FK_Lecon_Eleve", "Eleve");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Eleve>("TPAutoEcoleModel.FK_Lecon_Eleve", "Eleve", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TPAutoEcoleModel", "FK_Lecon_Voiture", "Voiture")]
        public Voiture Voiture
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Voiture>("TPAutoEcoleModel.FK_Lecon_Voiture", "Voiture").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Voiture>("TPAutoEcoleModel.FK_Lecon_Voiture", "Voiture").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Voiture> VoitureReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Voiture>("TPAutoEcoleModel.FK_Lecon_Voiture", "Voiture");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Voiture>("TPAutoEcoleModel.FK_Lecon_Voiture", "Voiture", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TPAutoEcoleModel", Name="Voiture")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Voiture : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet Voiture.
        /// </summary>
        /// <param name="id">Valeur initiale de la propriété id.</param>
        /// <param name="modele">Valeur initiale de la propriété modele.</param>
        /// <param name="estVoiture">Valeur initiale de la propriété estVoiture.</param>
        public static Voiture CreateVoiture(global::System.Guid id, global::System.String modele, global::System.Boolean estVoiture)
        {
            Voiture voiture = new Voiture();
            voiture.id = id;
            voiture.modele = modele;
            voiture.estVoiture = estVoiture;
            return voiture;
        }

        #endregion

        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Guid _id;
        partial void OnidChanging(global::System.Guid value);
        partial void OnidChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String modele
        {
            get
            {
                return _modele;
            }
            set
            {
                OnmodeleChanging(value);
                ReportPropertyChanging("modele");
                _modele = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("modele");
                OnmodeleChanged();
            }
        }
        private global::System.String _modele;
        partial void OnmodeleChanging(global::System.String value);
        partial void OnmodeleChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean estVoiture
        {
            get
            {
                return _estVoiture;
            }
            set
            {
                OnestVoitureChanging(value);
                ReportPropertyChanging("estVoiture");
                _estVoiture = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("estVoiture");
                OnestVoitureChanged();
            }
        }
        private global::System.Boolean _estVoiture;
        partial void OnestVoitureChanging(global::System.Boolean value);
        partial void OnestVoitureChanged();

        #endregion

    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TPAutoEcoleModel", "FK_Lecon_Voiture", "Lecon")]
        public EntityCollection<Lecon> Lecon
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Lecon>("TPAutoEcoleModel.FK_Lecon_Voiture", "Lecon");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Lecon>("TPAutoEcoleModel.FK_Lecon_Voiture", "Lecon", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
